project:
  title: "money-in-football"
  execute-dir: project
  output-dir: _tmp
  post-render:
    - rsync -vau --remove-source-files _tmp/src/ output
    - find _tmp/ -type d -empty -delete

format: 
  gfm:
    toc: true
    toc-depth: 3
    fig-width: 12.5
    fig-height: 9
    fig-align: center
    warning: false

editor_options: 
  chunk_output_type: console